### ISSUE TITLE
Request: Leaderboards with options to add and remove statistics. 

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/ServerUtilities#111]
I assume? Some of the Leaderboards farm data from the player profiles directly. This would be a fun thing to add / remove our own Statistics to. For example if were a big community on Railroad usage, maybe a stat that shows our Minecraft travel distance. Maybe if were big into mining one that shows all the stone we have mined.

I think FTBU Original idea was going to be that, but I don't think it ever happen at least I'm not sure since I never went that far.

PS: Be nice this was on the server side, so it sync up to the client and not something I have to send players a new config, etc. I only say this because the trash can normally would hide on client side if disabled and is not doing that. 

Thanks.

**Comment by Lyfts** [comment]
No, trash can would not normally hide if disabled serverside. It never did that in FTBU, in fact none of the buttons did, and it won't do that there either.

Besides that I do like the idea and it looks fairly feasible to implement.
