### ISSUE TITLE
ERROR:When backup start,the server is closed

### ISSUE THREAD

**Issue by QianWJ411** [GTNewHorizons/ServerUtilities#112]
Only use mod:gtnhlib-0.5.7-pre,ServerUtilities-2.0.73-pre
[crash-2024-09-07_21.24.50-server.txt](https://github.com/user-attachments/files/16918459/crash-2024-09-07_21.24.50-server.txt)

**Comment by Lyfts** [comment]
Can you send fml-client-latest from the logs folder? You are somehow missing a library that vanilla 1.7.10 ships with

**Comment by QianWJ411** [comment]
[2024-09-07-6.log](https://github.com/user-attachments/files/16920206/2024-09-07-6.log)

**Comment by QianWJ411** [comment]
[fml-server-2.log](https://github.com/user-attachments/files/16920210/fml-server-2.log)

**Comment by Lyfts** [comment]
@QianWJ411 can you try with https://github.com/GTNewHorizons/ServerUtilities/releases/tag/2.0.76-pre
