### ISSUE TITLE
Server crash Ultramine.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/ServerUtilities#12]
After the server starts, at the very end of loading, the server crashes. I checked on the Thermos server and there is no crash.

https://pastebin.com/dFg6vMXz

**Comment by bombcar** [comment]
`field_71561_b` is `net/minecraft/command/CommandHandler`

**Comment by Pilad** [comment]
Ultramine is written differently than a thermos, perhaps there are no parts from the forge server there. I don't understand this issue. The fact remains that utilities plow on a thermos. On Ultramine ftb utilities versions FTBUtilities-1.7.10-1.0.18.3 / FTBLib-1.7.10-1.0.18.3 work well.

**Comment by Lyfts** [comment]
@Pilad can you upload full log? Also try turning off command override in config, that should let it launch.

**Comment by Lyfts** [comment]
Also is the source for whatever ultramine uses available anywhere? Or a jar I can decompile?
