### ISSUE TITLE
Chunk load isn't work properly in server (maybe

### ISSUE THREAD

**Issue by TmeeX** [GTNewHorizons/ServerUtilities#122]
mod version: 2.0.38
gtnh version: 2.5.1
I enable the chunk claim and chunk load in config and found chunk load seems like there's no job available.
My machine can;t work when i leave but if i use a rc chunkload bloack it can work normally
i ask other gtnh player play in single ,they say their server utilities can work rightly

**Comment by Lyfts** [comment]
Chunkloading works perfectly fine, but you have likely only enabled chunk claiming in config/didn't shift-click the chunk to load it. If nothing works you can always try deleting the default config that gtnh ships with.

**Comment by TmeeX** [comment]
thank you i will try

**Comment by TmeeX** [comment]
> Chunkloading works perfectly fine, but you have likely only enabled chunk claiming in config/didn't shift-click the chunk to load it. If nothing works you can always try deleting the default config that gtnh ships with.

thank you , i will try
