### ISSUE TITLE
Command to Force Ally via Admin Command to a Team.

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/ServerUtilities#136]
### Your GTNH Discord Username

StoneLegion

### Feature Request

On our server we got government land and not just 1 but a couple. I like to give permission to say 3 players who want to help with say the rail system.

I like to have a command where I could say /team ally Team1 Bob and now Bob would be an ally of Team1.

Hope this is a simple one. 

More fleshed out system be able to join multiple teams, permission system, etc. But I think that is for another time. 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by Georggi** [comment]
Maybe a bit easier to implement by adding /status_for command. /status already can change any user to Ally, but there is no /status_for
