### ISSUE TITLE
Exact Spawn Point (even under blocks and 1x1 location)

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/ServerUtilities#138]
### Your GTNH Discord Username

StoneLegion

### Feature Request

I had seen a mod while back for this, but it caused issues/conflicts. If I recall this would need to be done with the mixins? Not 100% sure, either way thought I request it :) 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by Lyfts** [comment]
Forge already has a setting for this, just set `spawnHasFuzz` to false in forge.cfg.
