### ISSUE TITLE
Tab List Names not correctly syncing Colors Up.

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/ServerUtilities#145]
### Your GTNH Discord Username

StoneLegion

### Mod Version

2.0.85

### Bug Report

![image](https://github.com/user-attachments/assets/796c92e3-1f95-438d-be46-c2a5731d8246)
(We have no Display Names that are white period)

Not sure how best to explain this. We have quite a few colored names and even prefix in the display names. I think the issue here is sometimes the display names are not syncing up correctly. If I AFK for a bunch of hours or people relog I think there names slowly sync up correctly.

It's an odd one, I don't have any mods or anything other then Server Utilities that should be messing with the Tab Names. 

Hopefully it's a simple one to track down, but might need 2-3 people online to actually test it. 

### Java Version

Java 8

### Mod List or GTNH Pack Version

GTNH 2.7.0 RC3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by Lyfts** [comment]
Do you mind testing if it syncs correctly after a player does /nick? If it does I know exactly what the problem is

**Comment by StoneLegion** [comment]
Thanks, sorry I ended up going to be during this time, just woke up now. Thanks again for the fix.
