### ISSUE TITLE
Syncing Display Name Changes to Tab Menu only Happens on Relogs.

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/ServerUtilities#149]
### Your GTNH Discord Username

StoneLegion

### Mod Version

2.0.88

### Bug Report

So I changed Benner's rank there to a new color. In chat it works fine, but the Tab List does not refresh or grab the new data. This was over several Minutes, not sure if there is any kind of automatic refresh. The way our Server works is we have a linked quest system to increase their ranks based on quest progression, so seeing tab list updated with the most recent info is quite useful to us.

Thank you. 

![image](https://github.com/user-attachments/assets/566298e4-c7ba-4bf1-ba97-81a00f6fc938)

### Java Version

Java 21

### Mod List or GTNH Pack Version

GTNH 2.7.0 Release

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by Lyfts** [comment]
It would sync if you edited it through the gui which is the recommended way to manage ranks anyways.

**Comment by Lyfts** [comment]
Ah wait you automated it via command... Yeah alright I'll make that sync it too

**Comment by StoneLegion** [comment]
Thanks, odd enough I did this via a command as well because I made him Mod why he has green rank so via GUI I gave him m1_ but it did not show up in the game yet. So might be both area's acting up?

But yeah 99% of ranks are via command :) Thanks.
