### ISSUE TITLE
Can't create a new team without op permission at Thermos-Unoffical server

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/ServerUtilities#23]
![QQ截图20231212140721](https://github.com/GTNewHorizons/ServerUtilities/assets/33470743/e9b86cf2-f5b8-4349-8c54-aff71b3ff940)

**Comment by Lyfts** [comment]
I think that might be a problem with how the permissions is set through whatever thermos uses.
The command is allowed by all when our permission system is turned off.

**Comment by boubou19** [comment]
Thermos prints out all the detected permission nodes in the logs. Try checking it and adding the SU permission nodes to the default group of your server.

**Comment by XeonKA** [comment]
Works now,thanks!

**Comment by CrazyNutLz** [comment]
> Works now,thanks!

Can you tell me how you solved it?
