### ISSUE TITLE
Issues with ranks/permissions

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/ServerUtilities#32]
https://discord.com/channels/181078474394566657/603348502637969419/1204293261032685578

![image](https://github.com/GTNewHorizons/ServerUtilities/assets/11356565/35ddc48a-e649-495d-a886-76f4aaf30bdb)
custom cooldown and warmup times dont work for any of the commands that i've set for spawn or home

**Comment by Lyfts** [comment]
The format for the warmup/cooldown is incorrect here. If in doubt use /dump_permissions the file it makes shows everything there is to know about the various permission nodes including the allowed values.

This should definitely be documented better though so I'll leave the ticket open. I'll add some documentation to the wiki (soon™).

If anyone else happens to see this and wants to document something on the repo's wiki they can do so by forking the repo and adding a .MD file with the info to the wiki folder. Afterwards you just make a pr and it'll sync when merged.

**Comment by brandyyn** [comment]
> The format for the warmup/cooldown is incorrect here. If in doubt use /dump_permissions the file it makes shows everything there is to know about the various permission nodes including the allowed values.


![image](https://github.com/GTNewHorizons/ServerUtilities/assets/11356565/7510fbed-fd06-4178-adfb-bb6371d5a1ce)

**Comment by Lyfts** [comment]
You probably either have it turned off in config or are on a server and not op.

**Comment by brandyyn** [comment]
> You probably either have it turned off in config or are on a server and not op.

oooh thank you, i didn't realize i disabled it in the config. thank you, will test rank perms now

**Comment by brandyyn** [comment]
> The format for the warmup/cooldown is incorrect here. If in doubt use /dump_permissions the file it makes shows everything there is to know about the various permission nodes including the allowed values.
> 
> This should definitely be documented better though so I'll leave the ticket open. I'll add some documentation to the wiki (soon™).
> 
> If anyone else happens to see this and wants to document something on the repo's wiki they can do so by forking the repo and adding a .MD file with the info to the wiki folder. Afterwards you just make a pr and it'll sync when merged.

what am i doing wrong? it's exactly the same as the permissions dump

![image](https://github.com/GTNewHorizons/ServerUtilities/assets/11356565/f43fe815-68e9-464a-846c-a393355aca9f)

**Comment by Caedis** [comment]
try "120s"

**Comment by Lyfts** [comment]
I think it has a hard cap of 1 min which should probably be increased. You do however still have to define it as either 60s or 1m not just 60. Anything above is just gonna default back to the max.

**Comment by brandyyn** [comment]
> I think it has a hard cap of 1 min which should probably be increased. You do however still have to define it as either 60s or 1m not just 60. Anything above is just gonna default back to the max.

![image](https://github.com/GTNewHorizons/ServerUtilities/assets/11356565/9d005d64-e677-46b7-98d7-3133c54f1d49)
yep, works now, thank you. 

one last thing, could the messages be consolidated into one message or toast? like above hotbar like you guys do for entering claims? it fills up the chat extremely quickly

**Comment by brandyyn** [comment]
thank you @Lyfts, you can close this thread now i guess. just please remove the hard cap on the warmup for me and add the x/y cfg positioning in my other issue. thank you so much for everything. <3
