### ISSUE TITLE
Can't change the leaderboard icon

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/ServerUtilities#36]
The image isn't present in the assets folder, i'm using a texturepack to change the rest of the icons, but leaderboards seems to be using the sign item? 

![image](https://github.com/GTNewHorizons/ServerUtilities/assets/11356565/e8220619-e155-4657-b326-7330d49dc11a)

**Comment by Lyfts** [comment]
Fixed by https://github.com/GTNewHorizons/ServerUtilities/pull/35

**Comment by brandyyn** [comment]
> Fixed by #35

also, in the same vein as this, i don't know if it's just my pack or what but is there any chance or way to fix the gap between the server utilities icons and my inventory?

**Comment by Lyfts** [comment]
Pretty sure that's something in your pack causing it. If you can figure out which mod causes it feel free to make a new ticket.

**Comment by brandyyn** [comment]
> Pretty sure that's something in your pack causing it. If you can figure out which mod causes it feel free to make a new ticket.

Is there no chance there could be a X and Y configurator in the config file?


 (Move server utilities +10 pixels on the x axis)
