### ISSUE TITLE
Request to adjust icons position by x/y axis in config

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/ServerUtilities#37]
![image](https://github.com/GTNewHorizons/ServerUtilities/assets/11356565/dff182bd-0a45-4e77-b554-cc237a5c6b75)

For some reason, in my pack, there's a huge gap between the inventory and the icons, I'm not sure what's causing it or if it's a bug with the mod itself as I haven't tested it by itself, but I think a config option would be great for cases like this. 

I tried to edit the json files in the mod itself and changed the X value of the teams icon(the only value present) but it didn't change the position of the icon

**Comment by brandyyn** [comment]
i did actually find the culprit for this, it is the satchels mod by @makamys, and it is definitely a mod i want to keep using, i think the best course of action is to implement an x/y config option

**Comment by Lyfts** [comment]
Fixed by https://github.com/GTNewHorizons/ServerUtilities/pull/58
