### ISSUE TITLE
explosions do not turn off

### ISSUE THREAD

**Issue by Velas8555** [GTNewHorizons/ServerUtilities#50]
the ServerUtilities mod does not disable explosions on the server in captured chunks
![Screenshot_104](https://github.com/GTNewHorizons/ServerUtilities/assets/117538143/ca5c9287-123c-4043-bfef-ecb1786247cb)

**Comment by Velas8555** [comment]
> the ServerUtilities mod does not disable explosions on the server in captured chunks ![Screenshot_104](https://private-user-images.githubusercontent.com/117538143/313025962-ca5c9287-123c-4043-bfef-ecb1786247cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjExMTMsIm5iZiI6MTcxMDQ2MDgxMywicGF0aCI6Ii8xMTc1MzgxNDMvMzEzMDI1OTYyLWNhNWM5Mjg3LTEyM2MtNDA0My1iZmVmLWVjYjE3ODYyNDdjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwMDAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2Q4YWExNjA4YzBiM2ZhZTM0MzgzZDgwYzA1MDk4OWVjN2UzNDRhNTA5ZTlhNzU4MTdhMGY2ZDc3YmFlYmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZrR18W740WG7j4iKD45E0CuUTUcgPpRF0ju1y0ENT1A)

**Comment by chochem** [comment]
If you run the server, can you check the config? (/serverutilites/serverutilities.cfg, then world->enable_explosions)

There are 3 options as I understand. Teams can only decided for themselves on 'default' otherwise explosions are on for everybody ('true') or off for everybody ('false').

**Comment by Velas8555** [comment]
![Screenshot_104](https://github.com/GTNewHorizons/ServerUtilities/assets/117538143/1f25f443-7cbe-4f80-9799-f9bd73e46463)

and what does the server settings have to do with it, if it says that it should disable explosions in captured chunks, it turns out not to be a server mod. For each house separately, for each group, it must work separately. I'm alone, I'm privating the territory and turning on or off the settings anyway there are explosions

**Comment by chochem** [comment]
changing that config does not change it?

hmm, a bit of a side note. But probably the teams setting should not show ingame if the config is set to false or true.

**Comment by Velas8555** [comment]
serverutilities

**Comment by Lyfts** [comment]
If you truly had that setting set to false when the explosion occured then that is a problem. It is however not a problem I'm able to reproduce.

**Comment by Velas8555** [comment]
The teams setting should not be displayed in the game,true. This is how I should do it

**Comment by Velas8555** [comment]
I check so I went into a single-player game, seized the territory, turned off the explosions, took Industrial dynamite and blew it up in the captured territory. with different settings, the explosions do not disappear in the same way

**Comment by Velas8555** [comment]
I did not understand why to reproduce if you need to fix it on the GTNH 2.5.1 client version does not work

**Comment by Velas8555** [comment]
ServerUtilities   
https://disk.yandex.by/d/--tyewsECxXogA

**Comment by Velas8555** [comment]
everything works fine, I just had to say that it only works on GREGTECH mechanisms
