### ISSUE TITLE
Config file should move to .minecraft/configs

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/ServerUtilities#6]
just as title. the config file of ServerUtilities should move to .minecraft/configs for easily understanding.
example:
.minecraft/configs/ServerUtilities/serverutils.cfg
.minecraft/configs/ServerUtilities/serverutilslib.json
.minecraft/configs/ServerUtilities/client.json

**Comment by Ethryan** [comment]
This might happen if the rewrite is successful.
