### ISSUE TITLE
Player can't be found crash (Custom Modpack Not GTNH)

### ISSUE THREAD

**Issue by Rimusp** [GTNewHorizons/ServerUtilities#67]
I got a weird crash that happens when i try to generate a new world.

[fml-client-latest.log](https://github.com/GTNewHorizons/ServerUtilities/files/15176693/fml-client-latest.log)

if i remove server utilities it works

**Comment by Lyfts** [comment]
Can I get you to send a log without SU?
It looks like cofhcore is throwing an exception during PlayerLoggedInEvent which causes the event to never reach us.

**Comment by Rimusp** [comment]
OK after some testing its not su but some other mod it just works on 2 try to join a world and i removed su beforehand thats why i thought it was that.

sorry for that lmao
