### ISSUE TITLE
/nbtedit not working on block

### ISSUE THREAD

**Issue by adamsong** [GTNewHorizons/ServerUtilities#68]
Doing `/nbtedit` while looking at a block or `/nbtedit block <x> <y> <z>` with the coordinates of the block both fail to set the NBT of the block. `/nbtedit item` does work.

Originally noticed on railcraft tank, double checked with vanilla chest

Running version 2.0.35

**Comment by Lyfts** [comment]
Did you click the close button in the top right or did you use the escape button?

**Comment by shagejack** [comment]
Noticed the same issue with version 2.0.35 installed, `/nbtedit` just doesn't save the change anyway no matter I press ESC or use the accept button in the top right corner to exit.
