### ISSUE TITLE
[Feature Request] Don't include AFK'ing into total playtime in leaderboards

### ISSUE THREAD

**Issue by jusvit** [GTNewHorizons/ServerUtilities#74]
Would be cool if you have enabled the AFK option and you're afk to not include it in your playtime so you can get a more accurate reflection of playtime.

**Comment by Caedis** [comment]
Or have AFK time be its own stat

**Comment by Lyfts** [comment]
https://github.com/GTNewHorizons/ServerUtilities/pull/93
