### ISSUE TITLE
[Request] Name Change

### ISSUE THREAD

**Issue by Elrol** [GTNewHorizons/ServerUtilities#85]
I just had someone on my Discord server ask me about this mod thinking it was the same as mine because the names are the same. I was simply wanting to see if you could add something to the name of the mod to differentiate them. Perhaps calling it something like GT Server Utilities or something. 

Our mods won't overlap, because mine is for 1.14.4+ where as yours is 1.7.10 - 1.12.2. I have had my mod on CurseForge since 2019 so I was hoping that you would be willing to work with me on this.

For reference, here is the link: [https://www.curseforge.com/minecraft/mc-mods/server-utilities](https://www.curseforge.com/minecraft/mc-mods/server-utilities)

**Comment by Glease** [comment]
We did notice your mod during the renaming phase. However we were unable to come up with a sensible alternative. This is basically just FTBU on 1710 but without

**Comment by Glease** [comment]
I did notice your mod during the renaming phase. however given the userbase didn't overlap and we couldn't come up with a sensible alternative (and GTserver utilities is a bad one. this is not gt specific), so we just stick to the first name that was ever raised by the team members

Not saying we won't ever rename, as I've mostly quit the development of this specific mod by now. just providing some information here

**Comment by Caedis** [comment]
Also, this mod is just for 1.7.10

**Comment by vizthex123** [comment]
would also be nice if this was on CurseForge. I randomly found it when pulling a hail mary and asking the KubeJS server about how to make a guide with FTB Utilities.

**Comment by Elrol** [comment]
Sorry for the delayed response. 

I haven't had anyone else asking about this on my end, so I am just going to close this lol

But thanks for taking the time to talk about this and clear it up.
